sudo: required

arch:
  - amd64
  - arm64
language: go
go:
  - 1.13.4

go_import_path: github.com/alibaba

script:
  - pwd
  - ls
  - git clone https://github.com/jagrati15/pouch
  - cd pouch
  - make build && make install
  - whereis pouchd
  - sudo cp bin/pouch /usr/local/bin
  - sudo cp bin/pouchd /usr/local/bin
  - hack/install/install_containerd.sh
  - sudo whereis containerd
  - sudo cp bin/containerd /usr/local/bin
  - sudo pouchd
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
