sudo: required

#language: go

#go:
#  - 1.13.4

script:
  - pwd
  - echo $HOME
  - ls
  - pwd
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
    sudo wget https://dl.google.com/go/go1.12.linux-arm64.tar.gz;
    sudo tar -xf go1.12.linux-arm64.tar.gz;
    sudo mv go /usr/bin;
    export GOROOT=/usr/bin/go;
    export GOPATH=$HOME/go;
    export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    else
    sudo wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz;
    sudo tar -xf go1.12.linux-amd64.tar.gz;
    sudo mv go /usr/bin;
    export GOROOT=/usr/bin/go;
    export GOPATH=$HOME/go;
    export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    fi
  - echo $GOPATH
  - echo $PATH
  - sudo mkdir -p ${GOPATH}/src/github.com/alibaba/
  - cd ${GOPATH}/src/github.com/alibaba/
  - sudo git clone https://github.com/Abhisheknishant/pouch
  - cd pouch
  - sudo whereis go
  - whereis go
  - sudo go version
  - sudo PATH="$PATH" go version
  - go version
  - sudo go version
  - sudo make build
  - sudo make install
  - sudo rm -rf /usr/local/go
  #- sudo apt-get install -yq golang
  - sudo whereis pouchd
  - sudo whereis go
  - whereis go
  - sudo go version
  - go version
  - sudo cp ${GOPATH}/bin/pouch /usr/local/bin
  - sudo cp ${GOPATH}/bin/pouchd /usr/local/bin
  - cd ..
  - sudo git clone https://github.com/Abhisheknishant/containerd
  - cd containerd
  - sudo make BUILDTAGS=no_cri
  - sudo make install
  - cd ../../../..
  - sudo whereis containerd
  - sudo cp ${GOPATH}/bin/containerd /usr/local/bin
  - sudo pouchd
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
