sudo: required

arch:
  - amd64
#language: go

script:
  - pwd
  - echo $HOME
  - ls
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
    sudo wget https://dl.google.com/go/go1.12.linux-arm64.tar.gz;
    sudo tar -xf go1.12.linux-arm64.tar.gz;
    sudo mv go /usr/bin;
    export GOROOT=/usr/local/go;
    export GOPATH=$HOME/go;
    export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    else
    sudo wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz;
    sudo tar -xf go1.12.linux-amd64.tar.gz;
    sudo mv go /usr/local;
    export GOROOT=/usr/bin/go;
    export GOPATH=$HOME/go;
    export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    fi
  - pwd
  - echo $GOPATH
  - sudo mkdir -p ${GOPATH}/src/github.com/alibaba/
  - cd ${GOPATH}/src/github.com/alibaba/
  - sudo git clone https://github.com/jagrati15/pouch
  - cd pouch
  - sudo whereis go
  - whereis go
  - sudo apt-get install -y golang
  - sudo make build && make install
  - sudo whereis pouchd
  - sudo whereis go
  - whereis go
  - sudo cp bin/pouch /usr/local/bin
  - sudo cp bin/pouchd /usr/local/bin
  - PATH="$PATH" sudo hack/install/install_containerd.sh
  - sudo whereis containerd
  - sudo cp bin/containerd /usr/local/bin
  - sudo pouchd
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
